### ISSUE TITLE
序列号溢出后没有重置

### ISSUE THREAD

**Issue by eric-mu** [holdno/snowFlakeByGo#4]
序列号w.number在溢出单位时间内的生成上限，等到下一个时间戳后，没有重置为0，造成序列号溢出到workerid区域了
![image](https://user-images.githubusercontent.com/53249590/146530436-fb118341-8332-4f2d-bb94-24cef06585cd.png)

**Comment by holdno** [comment]
fixed [v1.0.0](https://github.com/holdno/snowFlakeByGo/tree/v1.0.0)
